### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II-CSX/csxtools#14]
@stuwilkins Are you ready to tag a release? If so, I will deploy it on Jupyterhub. cc @vivekthampy

**Comment by stuwilkins** [comment]
Once @vivekthampy rebases again against master and does the comments on the pull request I will tag.

**Comment by stuwilkins** [comment]
Tagged v0.1.0 today. Thanks @danielballan !

**Comment by stuwilkins** [comment]
Attn @vivekthampy @cmazzoli @ambarb 

This is now on the jupyter hub for all to use.
