### ISSUE TITLE
Should stacksum return a warning if encounters NaN's?

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II-CSX/csxtools#45]
We might consider raising a warning if stacksum encounters NaN's:

"stacksum encountered NaN values and excluded these values from the sum effectively assuming NaN = 0.
Consider using the number of points, which is returned as the second argument in the tuple, to renormalize the image."

**Comment by tacaswell** [comment]
The PR looks reasonable, but in general warnings are never read.  If you want to get peoples attention, raise an exception.

**Comment by mpmdean** [comment]
I should have closed this a while ago, but am doing so now.
