### ISSUE TITLE
Refactor to align with changes in databroker

### ISSUE THREAD

**Issue by stuwilkins** [NSLS-II-CSX/csxtools#56]

**Comment by danielballan** [comment]
As far as you know, is csxtools broken by our API changes, invoking our deprecations, or none of the above?

**Comment by stuwilkins** [comment]
All of the above

**Comment by danielballan** [comment]
OK. If this is disruptive to user operations and you lack the bandwidth to address it in time, I'm willing to help.

**Comment by stuwilkins** [comment]
@danielballan don't worry, I think it is good that I (we) have to change this. I will work on this from home wed/thurs to get all inline. I may need help with handlers etc? Where is the idea of adding a config file for defining how the handlers get assigned to specs? That is by biggest need at the moment in this respect (CSXTOOLS)

**Comment by stuwilkins** [comment]
Oh and we do need to get FastCCD data into databroker correctly....

**Comment by danielballan** [comment]
> Where is the idea of adding a config file for defining how the handlers get assigned to specs?

Nominally implemented and deployed, but when I looked up the relevant code to back up on that claim, I found that it's undocumented, untested, and broken. All those problems are addressed in https://github.com/NSLS-II/databroker/pull/305, which will be merged and deployed at CSX today.

**Comment by danielballan** [comment]
> Oh and we do need to get FastCCD data into databroker correctly....

With regard to the timing of when documents are created?

**Comment by danielballan** [comment]
> @danielballan don't worry, I think it is good that I (we) have to change this. I will work on this from home wed/thurs to get all inline.

csxtools still has a filestore import, which made it un-importable in the 2017-3 conda environment. It would be nice to fix it in time for 2018-1. Do you need help with that?

**Comment by danielballan** [comment]
attn @wen-hu

**Comment by ambarb** [comment]
unsure if this particualr instance was ever fixed.  Noting that we used `databroker 0.13.0` doesn't play nice with the default HDF5 handler for area-detector.  Only get_table() seems to work (which is why CSXtools still uses it.  Testing with @danielballan confirmed handler issue.  However, the issue is not present in `databroker 1.0.2`

@leofang FYI, but I don't think we are ready to make the switch yet, just thought you would be interested.

**Comment by ambarb** [comment]
stale

addressed also with https://github.com/NSLS-II-CSX/csxtools/pull/86
