### ISSUE TITLE
Cannot specify more than one dark image in get_fastccd_images

### ISSUE THREAD

**Issue by mpmdean** [NSLS-II-CSX/csxtools#60]
The current srv1 kernal on CSX cannot specify more than one dark image in get_fastccd_images

`
from databroker import DataBroker as db
from csxtools.utils import get_fastccd_images

old_scan_no = 85528
slicerator = get_fastccd_images(db[old_scan_no], (db[old_scan_no-1, old_scan_no+1], None, None))
`

Throws an error

AttributeError Traceback (most recent call last)
in ()
3
4 old_scan_no = 85528
----> 5 slicerator = get_fastccd_images(db[old_scan_no], (db[old_scan_no-1, old_scan_no+1], None, None))

/opt/conda_envs/analysis-2018-1.0/lib/python3.6/site-packages/csxtools/utils.py in get_fastccd_images(light_header, dark_headers, flat, gain, tag, roi)
85 # Get the images
86
---> 87 bgnd_events = _get_images(d, tag, roi)
88
89 # We assume that all images are for the background

/opt/conda_envs/analysis-2018-1.0/lib/python3.6/site-packages/csxtools/utils.py in _get_images(header, tag, roi)
179 def _get_images(header, tag, roi=None):
180 t = ttime.time()
--> 181 images = header.db.get_images(header, tag)
182 t = ttime.time() - t
183 logger.info("Took %.3f seconds to read data using get_images", t)

AttributeError: 'list' object has no attribute 'db'

I believe this comes from this change:

-def _get_images(header, tag, roi=None, handler_override=None):
+def _get_images(header, tag, roi=None):
     t = ttime.time()
-    images = get_images(header, tag, handler_override=handler_override)
+    images = header.db.get_images(header, tag)
results in an incompatibility described below. Or at least something that previously worked now does not. The variable header becomes a list if one wants to use.

**Comment by stuartcampbell** [comment]
@licode Can you have a look into this ?

**Comment by licode** [comment]
sure, I am on this.

**Comment by licode** [comment]
I think this should work
```
slicerator = get_fastccd_images(db[old_scan_no], (db[old_scan_no-1,old_scan_no+1]))
```
(db[old_scan_no-1,old_scan_no+1], None, None) is not 1d tuple.

**Comment by mpmdean** [comment]
I think we're in agreement. The code was changed from using the get_table function imported at the start of the module to access the same functionality via the .table() attribute of the input object. 

Maybe there are some speed or other reasons for this? If not, my instinct would be to put it back as it was?

**Comment by licode** [comment]
sounds good. hdr.db.get_images should work with multiple headers, because nothing changed in db.get_images, we just linked it back to hdr. We only need a quick fix in csxtools. I am working a PR on this.

**Comment by licode** [comment]
https://github.com/NSLS-II-CSX/csxtools/pull/61

**Comment by ambarb** [comment]
Tested 
/opt/conda_envs/analysis-2018-2.1)
csxtools:  '0.1.13'

tested before debian 7 upgrade to 8 and it still seemed problematic.

tested this week after debian upgrade to 8 on all 3 servers and not this functionality appears to work without issue.
