### ISSUE TITLE
Separating images by events

### ISSUE THREAD

**Issue by vivekthampy** [NSLS-II-CSX/csxtools#7]
Right now get_fastccd_images gets the whole stack of images into one numpy array. Think it might be useful to have that broken up by events to plot scans (such as energy scans).

Working on this right now.

**Comment by stuwilkins** [comment]
Vivek… lets discuss first what we want with @ambarb and @cmazzoli and me before coding.

**Comment by tacaswell** [comment]
There is code for this in csxtools ex https://github.com/NSLS-II-CSX/csxtools/blob/master/csxtools/image_corr.py#L50

and this notebook : https://github.com/NSLS-II-CSX/notebooks/blob/add_csx/23-ID-1/image_correction_basic_xpcs_multitau.ipynb
