### ISSUE TITLE
Fix deprecation warnings on tests.

### ISSUE THREAD

**Issue by ambarb** [NSLS-II-CSX/csxtools#84]
```python
tests/test_image.py::test_images_mean
  /nsls2/users/abarbour/Repos/csxtools/tests/test_image.py:85: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    x = np.array([np.repeat(ii*np.ones(ii*100, dtype=np.float32), 400).reshape(

tests/test_image.py::test_images_sum
  /nsls2/users/abarbour/Repos/csxtools/tests/test_image.py:92: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
    x = np.array([np.repeat(ii*np.ones(ii*100, dtype=np.float32), 400).reshape(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by ambarb** [comment]
code to generate: 
```
python setup.py develop
pip install pytest coverage setuptools
python run_tests.py
coverage run run_tests.py 
coverage report -m
```

@danielballan would love to pair code to resolve this with csxtools upgrade

most recent documentation of errors in the PR https://github.com/NSLS-II-CSX/csxtools/pull/83

**Comment by ambarb** [comment]
this seems broken with numpy version `1.24.4` and integrated CI from GHA

fix this for this version of numpy

after that, check https://github.com/NSLS-II-CSX/csxtools/blob/master/requirements.txt to make sure that we enforce the earliest version that is compatible

**Comment by ambarb** [comment]
deprecation warnings are present (but unit tests maybe pass) for 
conda env `2023-1.2-py39-tiled`
`numpy.__version__ = '1.23.5'`

**Comment by padraic-shafer** [comment]
This appears to no longer be an issue with conda env `2023-1.2-py39-tiled`
https://github.com/padraic-shafer/csxtools/actions/runs/9183958306/job/25255505812

I've added PR #96 so that the unit tests for `csxtools` can run on recent conda environments when changes get pushed.

**Comment by ambarb** [comment]
great.  should we close the now?

**Comment by padraic-shafer** [comment]
That works for me.
